name: Build and Deploy Next.js to GitHub Pages

on:
  push:
    branches: [ backup/main ]  # ou 'main', troque aqui se precisar

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read    # para checkout
      pages: write      # para publicar no Pages
      id-token: write   # necessário para deploy-pages

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Build Next.js (static export)
        run: npm run build

      - name: Copy .nojekyll
        run: cp public/.nojekyll out/.nojekyll

      - name: Upload artifact for Pages
        uses: actions/upload-pages-artifact@v1
        with:
          path: out

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
