name: Build and Deploy Next.js to GitHub Pages

on:
  push:
    branches: [ backup/main ]  # ou 'main', onde você desenvolve

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read        # permite checkout
      pages: write          # permite deploy Pages
      id-token: write       # necessário internamente

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build production
        run: npm run build     # gera out/

      - name: Copy .nojekyll
        run: cp public/.nojekyll out/.nojekyll

      - name: Upload artifact for Pages
        uses: actions/upload-pages-artifact@v1
        with:
          path: out

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
