name: Build and Deploy Next.js to GitHub Pages

on:
  push:
    branches:
      - backup/main   # ou 'main', na sua convenção

jobs:
  pages:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node 18
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Build static export
        run: npm run build

      - name: Copy .nojekyll
        run: cp public/.nojekyll out/.nojekyll

      - name: Configure Pages
        uses: actions/configure-pages@v2

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: out

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
